server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka, http://localhost:9002/eureka
    # 是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
  instance:
    instance-id: consumer-feign-payment-8083
    # 访问eureka主页时显示ip地址
    prefer-ip-address: true

spring:
  application:
    name: consumer-feign-payment

# 设置feign客户端超时时间(OpenFeign默认支持ribbon)(单位：毫秒)
ribbon:
  # 指的是建立连接后从服务器读取到可用资源所用的时间
  ReadTimeout: 5000
  # 指的是建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间
  ConnectTimeout: 5000

